apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: expense
spec:
  containers:
  # docker run -d --name nginx nginx
  - name: debug
    image: joindevops/debug:v1
---
apiVersion: v1
kind: Service
metadata: 
  name: debug
  namespace: expense
spec:
  selector: 
    name: debug
  ports:
  - name: debug
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: debug1
    protocol: TCP
    port: 3306
    targetPort: 3306
    