apiVersion: v1
kind: Pod
metadata:
  name: one
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 60m
        memory: 100Mi
      limits:
        cpu: 100m 
        memory: 120Mi
        