apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: svc
  labels:
    new: yes
spec:
  selector:
    env: dev
  ports:
  - name: svc-port
    protocol: TCP
    port: 80
    targetPort: 80
