apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    envs: dev
spec:
  containers:
  - name: nginx
    image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: svc
  labels:
    new: yess
spec:
  type: NodePort
  selector:
    envs: dev
  ports:
  - name: svc-port
    protocol: TCP
    nodePort: 30011
    port: 80
    targetPort: 80
