apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: expense
  labels:
    project: expense
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev
  template: 
    metadata: 
      labels:
        project: expense
        environment: dev
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    environment: dev
spec:
  selector:
    project: expense
    environment: dev
  ports:
  - name: backend
    protocol: TCP
    port: 8080
    targetPort: 8080