apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    project: expense
    environment: dev
spec:  
  replicas: 2
  selector:   
    matchLabels:
      project: expense
      environment: dev
  template: 
    metadata:   
      labels:
        project: expense
        environment: dev
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1 
