apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    project: expense
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev  
  template: 
    metadata: 
      name: frontend
      labels:
        project: expense
        environment: dev
    spec:
      containers:
      - name: frontend
        image:
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespce: expense
  labels:
    project: expense
    environment: dev
  spec:
    type: LoadBalancer
    selector:
      project: expense
      environment: dev
    ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
